[project]
name = "openapi_sse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"

[project.scripts]
hello = "openapi_sse.main:main"